### ISSUE TITLE
Portrait details: Omit specific items (input Sam)

### ISSUE THREAD

**Issue by ThijsRU** [ThijsRU/Roman_Imperial_Portraits#48]
Sam will make a scheme that will show when the items with "No" can be omitted. 

•	Sommige zaken waarop het antwoord “No” is zijn niet zo relevant. Die specifieke zaken moet Sam even aanwijzen en bekijken welke er dan bijvoorbeeld niet getoond worden als deze niet van toepassing zijn.

**Comment by ThijsRU** [comment]
Zie:

def add_to_context(self, context, instance):
        """Add to the existing context"""

Hier kan het worden afgevangen.

**Comment by sam-heijnen** [comment]
Betreffende categorie weglaten als:
IF “re-carved” = NO 
IF “identity disputed” = NO 
IF “miniature” = NO 
IF “Statue” = NO 
IF “Bust” = NO 
IF “Toga” = NO 
IF “Capite velato” = NO 
IF “Cuirass” = NO 
IF “Enthroned” = NO 
IF “Beard” = NO 
IF “Paludamentum” = NO 
IF “Sword belt” = NO 
IF “Contabulata” = NO 
IF “Headgear” = NO 
IF “Corona laurea” = NO 
IF “Corona civica” = NO 
IF “Corona radiata” = NO

**Comment by sam-heijnen** [comment]
niet nodig in de nieuwe versie van de website

**Comment by ThijsRU** [comment]
DONE for now
